name = "one-drop-threads"
compatibility_date = "2024-01-01"

pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "one-drop-threads-db"
database_id = "4926ed8c-a387-4500-bc64-08e03662a678" # Replace with actual ID from `wrangler d1 create`

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "one-drop-threads-images"
